#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXft
Version  : 2.3.2
Release  : 12
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXft-2.3.2.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXft-2.3.2.tar.gz
Summary  : X FreeType library
Group    : Development/Tools
License  : HPND
Requires: libXft-lib
Requires: libXft-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32fontconfig)
BuildRequires : pkgconfig(32freetype2)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xrender)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xrender)

%description
Xft
X FreeType library
Xft version 2.1 was the first stand alone release of Xft, a library that
connects X applications with the FreeType font rasterization library. Xft
uses fontconfig to locate fonts so it has no configuration files.

%package dev
Summary: dev components for the libXft package.
Group: Development
Requires: libXft-lib
Provides: libXft-devel

%description dev
dev components for the libXft package.


%package dev32
Summary: dev32 components for the libXft package.
Group: Default
Requires: libXft-lib32

%description dev32
dev32 components for the libXft package.


%package doc
Summary: doc components for the libXft package.
Group: Documentation

%description doc
doc components for the libXft package.


%package lib
Summary: lib components for the libXft package.
Group: Libraries

%description lib
lib components for the libXft package.


%package lib32
Summary: lib32 components for the libXft package.
Group: Default

%description lib32
lib32 components for the libXft package.


%prep
%setup -q -n libXft-2.3.2
pushd ..
cp -a libXft-2.3.2 build32
popd

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do mv $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xft/Xft.h
/usr/include/X11/Xft/XftCompat.h
/usr/lib64/libXft.so
/usr/lib64/pkgconfig/xft.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXft.so
/usr/lib32/pkgconfig/32xft.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXft.so.2
/usr/lib64/libXft.so.2.3.2

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXft.so.2
/usr/lib32/libXft.so.2.3.2
